name: anapay_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  device_preview: ^1.3.1
  google_sign_in: ^6.2.1
  flutter_dotenv: ^6.0.0
  firebase_app_check: ^0.4.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

# Obfuscation configuration for release builds
build:
  obfuscate: true
  split-debug-info: build/app-debug-symbols
